# Generated by Django 4.2.1 on 2023-06-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='division',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='house',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stream',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
